.TH "netlabel-config" 8 "31 мая 2013" "paul@paul-moore.com" "Документация по NetLabel"
.\" //////////////////////////////////////////////////////////////////////////
.SH ИМЯ
.\" //////////////////////////////////////////////////////////////////////////
netlabel-config \- утилита настройки NetLabel
.\" //////////////////////////////////////////////////////////////////////////
.SH ОБЗОР
.\" //////////////////////////////////////////////////////////////////////////
.B netlabelctl
reset| load
.\" //////////////////////////////////////////////////////////////////////////
.SH ОПИСАНИЕ
.\" //////////////////////////////////////////////////////////////////////////
.P
Утилита настройки NetLabel, netlabel-config, это сценарий, который облегчает
системным администраторам работу по созданию, управлению и использованию сложных
конфигураций NetLabel. Сценарий netlabel-config использует утилиту netlabelctl(8)
и файл конфигурации /etc/netlabel.rules для загрузки сохранённой конфигурации
NetLabel в ядро, а также (при необходимости) для возврата конфигурации NetLabel ядра в состояние
по умолчанию.
.TP
.B reset
Удалить загруженную в ядро конфигурацию NetLabel и вернуть состояние NetLabel ядра к значениям по умолчанию.
.TP
.B load
Загрузить конфигурацию NetLabel, указанную в /etc/netlabel.rules, в ядро.
.\" //////////////////////////////////////////////////////////////////////////
.SH СООБЩЕНИЕ ПРИ ВЫХОДЕ
.\" //////////////////////////////////////////////////////////////////////////
Возвращает ноль при успешном завершении или значения errno при ошибках.
.\" //////////////////////////////////////////////////////////////////////////
.SH "ПРИМЕЧАНИЯ"
.\" //////////////////////////////////////////////////////////////////////////
.P
Подсистема NetLabel поддерживается в ядре Linux версии 2.6.19 и выше.
Статические (резервные) метки поддерживаются только в ядре Linux версии
2.6.25 и выше. Селекторы адресов для сопоставления доменов поддерживаются только в ядре
Linux версии 2.6.28 и выше, а CALIPSO/RFC5570 поддерживается только в ядре
Linux версии 4.8.0 и выше.
.P
Веб-сайт проекта NetLabel, на котором доступны дополнительные сведения, включая репозиторий исходного кода, находится по адресу https://github.com/netlabel. Пожалуйста, отправляйте сообщения об ошибках через сайт проекта или напрямую автору.
.\" //////////////////////////////////////////////////////////////////////////
.SH "СМОТРИТЕ ТАКЖЕ"
.\" //////////////////////////////////////////////////////////////////////////
.BR netlabelctl (8)
.\" //////////////////////////////////////////////////////////////////////////
.SH "АВТОРЫ"
.\" //////////////////////////////////////////////////////////////////////////
Paul Moore <paul@paul-moore.com>. Перевод на русский язык выполнила Герасименко Олеся <gammaray@basealt.ru>.
